#!/usr/bin/python3

import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "src"))
import installfedoraonzfs.pm


if __name__ == "__main__":
    sys.exit(installfedoraonzfs.pm.deploypackagesinchroot())
