#!/usr/bin/env python

import os
import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "src"))
import installfedoraonzfs


if __name__ == "__main__":
    sys.exit(installfedoraonzfs.deploy_zfs())
