#!/bin/bash

set -xe

MOCKLIB="$HOME/mockroot/lib"
MOCKCACHE="$HOME/mockroot/cache"

mountpoint -q "/var/lib/mock" || {
  mkdir -p "$MOCKLIB"
  mount --bind "$MOCKLIB" /var/lib/mock
}
mountpoint -q "/var/cache/mock" || {
  mkdir -p "$MOCKCACHE"
  mount --bind "$MOCKCACHE" /var/cache/mock
}

MOCKSOURCE=/etc/mock/fedora-23-x86_64.cfg
MOCKCONFIG=/etc/mock/fedora-23-x86_64-custom.cfg
MOCKCONFIGROOT=fedora-23-x86_64-custom

mkdir -p `dirname "$MOCKCONFIG"`
cat "$MOCKSOURCE" \
  | sed "s|^config_opts.'root'.*.|config_opts['root'] = '$MOCKCONFIGROOT'|" \
  > "$MOCKCONFIG"
echo "
config_opts['plugin_conf']['bind_mount_enable'] = True
config_opts['plugin_conf']['bind_mount_opts']['dirs'].append(('/dev', '/dev/' ))
config_opts['plugin_conf']['bind_mount_opts']['dirs'].append(('/dev/pts', '/dev/pts/' ))
config_opts['plugin_conf']['bind_mount_opts']['dirs'].append(('/dev/shm', '/dev/shm/' ))
" >> "$MOCKCONFIG"

ret=
test -d /var/lib/mock/"$MOCKCONFIGROOT"/root || /usr/bin/mock -r "$MOCKCONFIG" --init || ret=$?
test -n "$ret" || {
  /usr/bin/mock -r "$MOCKCONFIG" "$@" || ret=$?
}

umount /var/lib/mock
umount /var/cache/mock

exit $ret
