#!/bin/bash

set -xe

dnf install -y qubes-kernel-vm-support grub2-tools kernel dkms mock
kver=$(rpm -q kernel --queryformat "%{version}-%{release}.%{arch}")
dnf install -y kernel-devel-$kver
dkms autoinstall -k $kver
dracut -fv --kver $kver
grub2-mkconfig -o /boot/grub2/grub.cfg
# and at this point I am supposed to set qvm-prefs this-appvm -s kernel pvgrub2
# and then reboot the VM
