#!/bin/bash

set -xe

rpm -q kernel kernel-devel || {
  echo "error: vmpreparation never installed the kernel or kernel-devel packages"
  exit 2
}

test -d zfs-fedora-installer || git clone https://github.com/Rudd-O/zfs-fedora-installer.git
sudo -E zfs-fedora-installer/deploy-zfs
